version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # monte le script d'initialisation de la db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R00tp@ssw0rd
      MYSQL_DATABASE: WaterPilotApp
      MYSQL_USER: userWaterPilotApp
      MYSQL_PASSWORD: sm@rtg4rd3n

  api:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=dbuser
      - DB_PASSWORD=userWaterPilotApp
      - DB_NAME=WaterPilotApp
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

volumes:
  db_data:
